version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80" # host:container port
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
