server:
  port: 80
 
spring:
  mvc: # view setting 
    hiddenmethod:
      filter:
        enabled: true    
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html